FROM golang:1.24-alpine AS builder
RUN apk add --no-cache git
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 go build -o /opensearch-indexer ./cmd/opensearch-indexer/

FROM alpine:3.19
RUN apk add --no-cache ca-certificates
COPY --from=builder /opensearch-indexer /usr/local/bin/opensearch-indexer
ENTRYPOINT ["opensearch-indexer"]
